// COMMENTS ENTITY ACTIONS
export const UPDATE_COMMENTS_PANEL = 'UPDATE_COMMENTS_PANEL';
export const UPDATE_COMMENTS_PANEL_TEXT_INPUT =
  'UPDATE_COMMENTS_PANEL_TEXT_INPUT';
// END OF COMMENT ACTIONS
